import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import './assets/tailwind.css';
import { createPinia } from 'pinia'

createApp(App).use(createPinia()).use(router).mount('#app');





            // {
            //     id: '3',
            //     name: 'Катя',
            //     city: 'Москва',
            //     age : 24,
            //     height : 165,
            //     weight : 50,
            //     boobs : 3,
            //     hour1Price : 10000,
            //     hour2Price : 24000,
            //     nightPrice : 40000,
            //     category1 : 'Выезд',
            //     category2 : 'Апартаменты',
            //     category3 : 'Мальчишники',
            //     category4 : 'Health+',
            //     link: require('@/assets/landing/img3.jpg'),
            // },
            
            // {
            //     id: '4',
            //     name: 'Алина',
            //     city: 'Москва',
            //     age : 21,
            //     height : 170,
            //     weight : 53,
            //     boobs : 3,
            //     hour1Price : 10000,
            //     hour2Price : 24000,
            //     nightPrice : 40000,
            //     category1 : 'Выезд',
            //     category2 : 'Апартаменты',
            //     category3 : 'Мальчишники',
            //     category4 : 'Health+',
            //     link: require('@/assets/landing/img2.jpg'),
            // },
            // {
            //     id: '5',
            //     name: 'Алина',
            //     city: 'Москва',
            //     age : 21,
            //     height : 170,
            //     weight : 53,
            //     boobs : 3,
            //     hour1Price : 10000,
            //     hour2Price : 24000,
            //     nightPrice : 40000,
            //     category1 : 'Выезд',
            //     category2 : 'Апартаменты',
            //     category3 : 'Мальчишники',
            //     category4 : 'Health+',
            //     link: require('@/assets/landing/img2.jpg'),
            // },
            // {
            //     id: '6',
            //     name: 'Алина',
            //     city: 'Москва',
            //     age : 21,
            //     height : 170,
            //     weight : 53,
            //     boobs : 3,
            //     hour1Price : 10000,
            //     hour2Price : 24000,
            //     nightPrice : 40000,
            //     category1 : 'Выезд',
            //     category2 : 'Апартаменты',
            //     category3 : 'Мальчишники',
            //     category4 : 'Health+',
            //     link: require('@/assets/landing/img2.jpg'),
            // },
            // {
            //     id: '7',
            //     name: 'Алина',
            //     city: 'Москва',
            //     age : 21,
            //     height : 170,
            //     weight : 53,
            //     boobs : 3,
            //     hour1Price : 10000,
            //     hour2Price : 24000,
            //     nightPrice : 40000,
            //     category1 : 'Выезд',
            //     category2 : 'Апартаменты',
            //     category3 : 'Мальчишники',
            //     category4 : 'Health+',
            //     link: require('@/assets/landing/img2.jpg'),
            // },
            // {
            //     id: '8',
            //     name: 'Алина',
            //     city: 'Москва',
            //     age : 21,
            //     height : 170,
            //     weight : 53,
            //     boobs : 3,
            //     hour1Price : 10000,
            //     hour2Price : 24000,
            //     nightPrice : 40000,
            //     category1 : 'Выезд',
            //     category2 : 'Апартаменты',
            //     category3 : 'Мальчишники',
            //     category4 : 'Health+',
            //     link: require('@/assets/landing/img2.jpg'),
            // },
            // {
            //     id: '9',
            //     name: 'Алина',
            //     city: 'Москва',
            //     age : 21,
            //     height : 170,
            //     weight : 53,
            //     boobs : 3,
            //     hour1Price : 10000,
            //     hour2Price : 24000,
            //     nightPrice : 40000,
            //     category1 : 'Выезд',
            //     category2 : 'Апартаменты',
            //     category3 : 'Мальчишники',
            //     category4 : 'Health+',
            //     link: require('@/assets/landing/img2.jpg'),
            // },